language: objective-c
osx_image: xcode8

before_install:
   - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
   - xcodebuild test -project Gloss.xcodeproj -scheme GlossTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
   - pod lib lint --quick
